app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

employee/urls.py
from django.urls import path
from employee.views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name= 'employee'

urlpatterns =[
    #Login
    path('', Login.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout/logout.html'), name='logout'),
    path('change_password/', ChangePassword.as_view(), name="change_password"),
    #Employee
    path('employee/', login_required(EmployeeGenericView.as_view()), name="list_employee"),
    path('employee/new', login_required(EmployeeCreateView.as_view()), name="new_employee"),
    path('employee/<pk>/update', login_required(EmployeeUpdateView.as_view()), name='update_employee'),
    path('employee/<pk>/detail', login_required(EmployeeDetailView.as_view()), name='detail_employee'),
    path('employee/<pk>/delete', login_required(EmployeeDeleteView.as_view()), name='delete_employee'),
    #Requirements
    path('requirements/', login_required(RequirementsGenericView.as_view()), name="list_requirements"),
    path('requirements/new', login_required(RequirementsCreateView.as_view()), name="new_requirements"),
    path('requirements/<pk>/update', login_required(RequirementsUpdateView.as_view()), name='update_requirements'),
    path('requirements/<pk>/detail', login_required(RequirementsDetailView.as_view()), name='detail_requirements'),
    path('requirements/<pk>/delete', login_required(RequirementsDeleteView.as_view()), name='delete_requirements'),
    path('requirements/<pk>/report', login_required(MyDetailViewPDF.as_view()), name='report_requirements'),
    # path('requirements/<pk>/report', login_required(DynamicNameView.as_view()), name='report_requirements'),
    #Reasons
    path('reason/', login_required(ReasonGenericView.as_view()), name="list_reason"),
    path('reason/new', login_required(ReasonCreateView.as_view()), name="new_reason"),
    path('reason/<pk>/update', login_required(ReasonUpdateView.as_view()), name='update_reason'),
    path('reason/<pk>/detail', login_required(ReasonDetailView.as_view()), name='detail_reason'),
    path('reason/<pk>/delete', login_required(ReasonDeleteView.as_view()), name='delete_reason'),
    #Holidays
    path('holidays/', login_required(HolidaysGenericView.as_view()), name="list_holidays"),
    path('holidays/new', login_required(HolidaysCreateView.as_view()), name="new_holidays"), 
    path('holidays/<pk>/update', login_required(HolidaysUpdateView.as_view()), name='update_holidays'),
    path('holidays/<pk>/detail', login_required(HolidaysDetailView.as_view()), name='detail_holidays'),
    path('holidays/<pk>/delete', login_required(HolidaysDeleteView.as_view()), name='delete_holidays'),
    path('holidays/<pk>/report2', login_required(MyDetailViewPDF2.as_view()), name='report_holidays'),
    #Jefatura
    path('jefatura/', login_required(JefaturaGenericView.as_view()), name="list_jefatura"),
    path('jefatura/new', login_required(JefaturaCreateView.as_view()), name="new_jefatura"),
    path('jefatura/<pk>/update', login_required(JefaturaUpdateView.as_view()), name='update_jefatura'),
    path('jefatura/<pk>/detail', login_required(JefaturaDetailView.as_view()), name='detail_jefatura'),
    path('jefatura/<pk>/delete', login_required(JefaturaDeleteView.as_view()), name='delete_jefatura'),
    #Penalty
    path('penalty/', login_required(PenaltyGenericView.as_view()), name='list_penalty'),
    path('penalty/new', login_required(PenaltyCreateView.as_view()), name='new_penalty'),
    path('penalty/<pk>/update', login_required(PenaltyUpdateView.as_view()), name='update_penalty'),
    path('penalty/<pk>/detail', login_required(PenaltyDetailView.as_view()), name='detail_penalty'),
    path('penalty/<pk>/delete', login_required(PenaltyDeleteView.as_view()), name='delete_penalty'),
    #reportPenalty
    path('report/', login_required(ReportGenericView.as_view()), name='list_report_penalty'),
    #reportEmployee
    path('report/requirements', login_required(Report2GenericView.as_view()), name='list_report_permisos'),
]

employee/views.py
from django.views.generic import ListView, CreateView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from employee.forms import EmployeeForm, HolidayForm, JefaturaForm, LoginForm, PasswordChangeForm, PenaltyForm, RequirementForm, ReasonForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from employee.models import Employee, Jefatura, Penalty, Reason, Requirements, Holidays
from django.db.models import Sum, Q
from django.http import HttpResponseRedirect
import datetime


#Login
class Login(LoginView):
    template_name= 'login/login_form.html'
    form_class= LoginForm

class ChangePassword(PasswordChangeView):
    template_name= 'login/change_password.html'
    form_class= PasswordChangeForm
    success_url = '/employee/'


#Employe CRUD
class EmployeeGenericView(ListView):
    model = Employee
    paginate_by= 10
    context_object_name = 'employees'

    def get_queryset(self):
       result = super(EmployeeGenericView, self).get_queryset().order_by("-lastname")
       query = self.request.GET.get('search')
       if query:
           searchName = Employee.objects.filter(Q(identification__icontains=query)| Q(lastname__icontains=query)).order_by("-lastname")
           result = searchName
       else:
           result = Employee.objects.all()
       return result

class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm
    success_url= '/employee/'

class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm

    def get_success_url(self):
        return '/employee/'

class EmployeeDetailView(DetailView):
    model = Employee

class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = '/employee/'

#Requirements CRUD
class RequirementsGenericView(ListView):
    model = Requirements
    template_name= 'requirements/requirements_list.html'
    paginate_by= 10
    context_object_name = 'requirements'

    def get_queryset(self):
       result = super(RequirementsGenericView, self).get_queryset().order_by("-code")
       query = self.request.GET.get('search')
       if query:
           searchName = Requirements.objects.filter(Q(employee__lastname=query)|Q(code=query)).order_by("-code")
           result = searchName
       else:
           result = Requirements.objects.all()
       return result

class RequirementsCreateView(CreateView):
    model = Requirements
    template_name= 'requirements/requirements_form.html'
    form_class = RequirementForm
    success_url= '/requirements/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        requi = self.object
        dateEnd = requi.date_end
        dateStart = requi.date_start
        dif = dateEnd-dateStart
        minutes = dif.seconds / 60
        hours = divmod(minutes, 60)
        hd = hours[0]
        if hours[1]>40:
            hd = hd + 1
        requi.hours_discount = int(hd)
        requi.save()

        if requi.reason.penalty:
            Penalty.objects.create(hours_penalty=requi.hours_discount, observations=requi.reason.name,date=requi.date_requirement, requirement=requi)
        return HttpResponseRedirect(self.get_success_url())


class RequirementsUpdateView(UpdateView):
    model = Requirements
    template_name= 'requirements/requirements_form.html'
    form_class = RequirementForm

    def get_success_url(self):
        return '/requirements/'

class RequirementsDetailView(DetailView):
    model = Requirements
    template_name= 'requirements/requirements_detail.html'

class RequirementsDeleteView(DeleteView):
    model = Requirements
    success_url = '/requirements/'

#Reason CRUD
class ReasonGenericView(ListView):
    model = Reason
    paginate_by= 10
    template_name= 'reason/reason_list.html'
    context_object_name = 'reasons'

class ReasonCreateView(CreateView):
    model = Reason
    template_name= 'reason/reason_form.html'
    form_class = ReasonForm
    success_url= '/reason/'

class ReasonUpdateView(UpdateView):
    model = Reason
    template_name= 'reason/reason_form.html'
    form_class = ReasonForm
    def get_success_url(self):
        return '/reason/'

class ReasonDetailView(DetailView):
    model = Reason
    template_name= 'reason/reason_detail.html'

class ReasonDeleteView(DeleteView):
    model = Reason
    template_name= 'reason/reason_form.html'
    success_url = '/reason/'

#Holidays CRUD
class HolidaysGenericView(ListView):
    model = Holidays
    paginate_by= 10
    template_name= 'holidays/holidays_list.html'
    context_object_name = 'holidays'

    def get_queryset(self):
       result = super(HolidaysGenericView, self).get_queryset()
       query = self.request.GET.get('search')
       if query:
           result = Holidays.objects.filter(Q(employee__identification__icontains=query)| Q(employee__lastname__icontains=query)).order_by("-date_requirement")
       else:
           result = Holidays.objects.all().order_by("-date_job")
       return result

class HolidaysCreateView(CreateView):
    model = Holidays
    template_name= 'holidays/holidays_form.html'
    form_class = HolidayForm 
    success_url= '/holidays/'

    def get_context_data(self, **kwargs):
        context = super(HolidaysCreateView, self).get_context_data(**kwargs)
        context["employeeList"] = Employee.objects.all()
        employeeSelect = self.request.GET.get('employeeSelect')
        dateLastHolidays = self.request.GET.get('dateLastHolidays')
        if employeeSelect and dateLastHolidays:
            employee = Employee.objects.get(identification= employeeSelect)
            totalHoursPenalty = Penalty.objects.filter(requirement__employee__identification= employeeSelect, date__range=[dateLastHolidays, datetime.datetime.now()]).aggregate(Sum('hours_penalty'))
            try:
                hours_penalty = divmod(totalHoursPenalty["hours_penalty__sum"], 8)
                days = hours_penalty[0]
                hours = hours_penalty[1]
            except:
                days = 0
                hours = 0
            data = {'employee':employee, 'days': days, 'hours':hours}
            context['data']= data
        return context
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        holiday = self.object
        totalHoursPenalty = Penalty.objects.filter(requirement__employee__identification= holiday.employee.identification, date__range=[holiday.date_last_holidays, datetime.datetime.now()]).aggregate(Sum('hours_penalty'))
        hours_penalty = divmod(totalHoursPenalty["hours_penalty__sum"], 8)
        print(f'********{hours_penalty}')
        holiday.days_penalty = hours_penalty[0]
        day_solicitados = holiday.days + hours_penalty[0]
        if holiday.days_total - day_solicitados >= 0:
            holiday.days_take = day_solicitados
            holiday.days_pending =  holiday.days_total - holiday.days_take
            holiday.date_end = holiday.date_start + datetime.timedelta(days=holiday.days-1)
        else:
            holiday.days_take = holiday.days - hours_penalty[0]
            holiday.days_pending =  holiday.days_total - holiday.days
            holiday.date_end = holiday.date_start + datetime.timedelta(days=holiday.days-1) - datetime.timedelta(days=hours_penalty[0])

        holiday.entry_work = holiday.date_end + datetime.timedelta(days=1)
        holiday.save()
        return HttpResponseRedirect(self.get_success_url())

class HolidaysUpdateView(UpdateView):
    model = Holidays
    template_name= 'holidays/holidays_form.html'
    form_class = HolidayForm
    def get_success_url(self):
        return '/holidays/'

class HolidaysDetailView(DetailView):
    model = Holidays
    template_name= 'holidays/holidays_detail.html'

class HolidaysDeleteView(DeleteView):
    model = Holidays
    template_name= 'holidays/holidays_form.html'
    success_url = '/holidays/'

#Jefatura CRUD
class JefaturaGenericView(ListView):
    model = Jefatura
    paginate_by= 10
    template_name= 'jefatura/jefatura_list.html'
    context_object_name = 'jefaturas'

    def get_queryset(self):
       result = super(JefaturaGenericView, self).get_queryset()
       query = self.request.GET.get('search')
       if query:
           searchName = Jefatura.objects.filter(Q(description__icontains=query))
           result = searchName
       else:
           result = Jefatura.objects.all()
       return result

class JefaturaCreateView(CreateView):
    model = Jefatura
    template_name= 'jefatura/jefatura_form.html'
    form_class = JefaturaForm
    success_url= '/jefatura/'

class JefaturaUpdateView(UpdateView):
    model = Jefatura
    template_name= 'jefatura/jefatura_form.html'
    form_class = JefaturaForm
    def get_success_url(self):
        return '/jefatura/'

class JefaturaDetailView(DetailView):
    model = Jefatura
    template_name= 'jefatura/jefatura_detail.html'

class JefaturaDeleteView(DeleteView):
    model = Jefatura
    template_name= 'jefatura/jefatura_form.html'
    success_url = '/jefatura/'

#ReportPDF requerimiento
class MyDetailViewPDF(DetailView):
    # vanilla Django DetailView
    model = Requirements
    template_name = 'report/requirementsReport.html'

#ReportPDFHolidays
class MyDetailViewPDF2(DetailView):
    # vanilla Django DetailView
    model = Holidays
    template_name = 'report/holidaysReport.html'

    def get_context_data(self, **kwargs):
        object = super().get_context_data(**kwargs)
        date_diff = object['object'].date_end - object['object'].date_start
        object['date_diff'] = date_diff.days + 1
        # object['date_dif']= self.request.GET.get('days')-self.request.GET.get('days_penalty')
        return object

class PenaltyGenericView(ListView):
    model = Penalty
    paginate_by= 10
    template_name= 'penalty/penalty_list.html'
    context_object_name = 'penalties'

    def get_queryset(self):
        return super().get_queryset().order_by('-requirement__code')

employee/templates/holidays/holidays_detail.html
{% extends 'base.html' %} 
{% block sidebar %} 
{% include 'sidebar.html' %} 
{% endblock %} 

{% block content %}
<div class="card me-5 ms-5 mt-3 mb-3">
    <div class="card-header d-flex ">
        <h5 class="card-title ms-2">Vacaciones</h5>
    </div>
    <div class="card-body">
        <p>Esta seguro que desea eliminar las vacaciones de <strong>{{ object.employee.lastname }} {{ object.employee.name }}</strong>?</p>
        <form method="post" action="{% url 'employee:delete_holidays' object.id %}">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a href="{% url 'employee:list_holidays' %}" class="btn btn-secondary">Regresar</a>
        </form>
    </div>
</div>
{% endblock %}

employee/templates/holidays/holidays_form.html
{% extends 'base.html' %}

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock %}

{% block content %}
<div class="m-3 me-5 ms-5">
    <div class="card">
        <div class="card-body">
            <div class="container">
                <form method="GET" action="{% url 'employee:new_holidays' %}">
                    <div class="mb-3">
                        <label for="form-label">Empleado</label>
                        <input class="form-control" list="datalistEmployeeHolidays" name="employeeSelect"
                            placeholder="Buscar por CI">
                        <datalist id="datalistEmployeeHolidays">
                            {% for e in employeeList %}
                            <option value="{{e.identification}}">
                                {{e.lastname}} {{e.name}}
                            </option>
                            {% endfor %}
                        </datalist>
                    </div>
                    <div class="mb-3">
                        <label for="form-label">Ultima fecha de vacaciones.</label>
                        <input class="form-control" type="date" name="dateLastHolidays">
                    </div>
                    <button class="btn btn-dark" type="submit">Buscar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% if data %}
<div class="m-3 me-5 ms-5">
    <table class="table table-bordered">
        <thead>
          <tr>
            <th rowspan="2">Empleado</th>
            <th colspan="2">Total de horas de permiso</th>
          </tr>
          <tr>
            <th>Días</th>
            <th>Horas</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{data.employee.lastname}} {{data.employee.name}}</td>
            <td>{{data.days}}</td>
            <td>{{data.hours}}</td>
          </tr>
        </tbody>
      </table>
</div>
{% endif %}
<div class="card me-5 ms-5 mt-3 mb-3">
    <div class="card-header">
        <h5 class="card-title">Vacaciones</h5>
    </div>
    <div class="card-body">
        <form method="post"> {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">
                    {{field.label}}
                    {% if field.field.required %}<span class="text-danger">*</span>{% endif %}
                </label>
                {{field}}
            </div>

            {% endfor %}
            <input class="visually-hidden" type="text" value="{{data.days}}" name="days_penalty">

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a href="{% url 'employee:list_holidays' %}" class="btn btn-secondary">Regresar</a>
        </form>
    </div>
</div>
{% endblock %}

employee/templates/holidays/holidays_list.html
{% extends 'base.html' %} 

{% block sidebar %} 
{% include 'sidebar.html' %} 
{% endblock %} 

{% block content %}
<div class="m-3">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <a href="{% url 'employee:new_holidays' %}" class="btn btn-primary"><i class="fa fa-plus-circle"></i>
                Agregar Vacaciones</a>
                <form method="GET" action="{% url 'employee:list_holidays' %}">
                    <div class="input-group">
                        <input type="text" class="form-control m-0" placeholder="Buscar por CI o apellido" name="search">
                        <button class="btn btn-outline-primary btn-sm" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </form>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped">
                <thead class="bg-dark">
                    <tr class="text-center text-light">
                        <th scope="col">Empleado</th>
                        <th scope="col">CI</th>
                        <th scope="col">Cargo</th>
                        <th scope="col">Ultima fecha de vacaciones anterior</th>
                        <th scope="col">Fecha a oficio</th>
                        <th scope="col">Fecha de Inicio</th>
                        <th scope="col">Fecha de Fin</th>
                        <th scope="col">Entrada al Trabajo</th>
                        <th scope="col">Días de Vacaciones Solicitadas</th>
                        <th scope="col">Días contabilizados por permisos</th>
                        <th scope="col">Días de Vacaciones Totales</th>
                        <th scope="col">Días pendientes de Vacaciones</th>
                        <th scope="col">Periodo</th>
                        <th scope="col" class="text-center">Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for holidays in holidays %}
                    <tr class="text-center">
                        <td>{{holidays.employee.name}} {{holidays.employee.lastname}}</td>
                        <td>{{holidays.employee.identification}}</td>
                        <td>{{holidays.position}}</td>
                        <td>{{holidays.date_last_holidays}}</td>
                        <td>{{holidays.date_job}}</td>
                        <td>{{holidays.date_start}}</td>
                        <td>{{holidays.date_end}}</td>
                        <td>{{holidays.entry_work}}</td>
                        <td>{{holidays.days}}</td>
                        <td>{{holidays.days_penalty}}</td>
                        <td>{{holidays.days_take}}</td>
                        <td>{{holidays.days_pending}}</td>
                        <td>{{holidays.period}}</td>
                        
                        <td class="d-flex justify-content-center flex-column">
                            <!-- <div class="mb-1">
                                <a class="btn btn-primary" href="{% url 'employee:update_holidays' holidays.id %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </div> -->
                            <div class="mb-1">
                                <a class="btn btn-danger" href="{% url 'employee:detail_holidays' holidays.id %}"><i
                                        class="fa fa-trash" aria-hidden="true"></i></a>
                            </div>
                            <div>
                                <a class="btn btn-success" href="{% url 'employee:report_holidays' holidays.id %}"><i
                                        class="fa fa-print" aria-hidden="true"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% include 'paginator.html' %}
    </div>

</div>
{% endblock %}