app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

employee/urls.py
from django.urls import path
from employee.views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name= 'employee'

urlpatterns =[
    #Login
    path('', Login.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout/logout.html'), name='logout'),
    path('change_password/', ChangePassword.as_view(), name="change_password"),
    #Employee
    path('employee/', login_required(EmployeeGenericView.as_view()), name="list_employee"),
    path('employee/new', login_required(EmployeeCreateView.as_view()), name="new_employee"),
    path('employee/<pk>/update', login_required(EmployeeUpdateView.as_view()), name='update_employee'),
    path('employee/<pk>/detail', login_required(EmployeeDetailView.as_view()), name='detail_employee'),
    path('employee/<pk>/delete', login_required(EmployeeDeleteView.as_view()), name='delete_employee'),
    #Requirements
    path('requirements/', login_required(RequirementsGenericView.as_view()), name="list_requirements"),
    path('requirements/new', login_required(RequirementsCreateView.as_view()), name="new_requirements"),
    path('requirements/<pk>/update', login_required(RequirementsUpdateView.as_view()), name='update_requirements'),
    path('requirements/<pk>/detail', login_required(RequirementsDetailView.as_view()), name='detail_requirements'),
    path('requirements/<pk>/delete', login_required(RequirementsDeleteView.as_view()), name='delete_requirements'),
    path('requirements/<pk>/report', login_required(MyDetailViewPDF.as_view()), name='report_requirements'),
    # path('requirements/<pk>/report', login_required(DynamicNameView.as_view()), name='report_requirements'),
    #Reasons
    path('reason/', login_required(ReasonGenericView.as_view()), name="list_reason"),
    path('reason/new', login_required(ReasonCreateView.as_view()), name="new_reason"),
    path('reason/<pk>/update', login_required(ReasonUpdateView.as_view()), name='update_reason'),
    path('reason/<pk>/detail', login_required(ReasonDetailView.as_view()), name='detail_reason'),
    path('reason/<pk>/delete', login_required(ReasonDeleteView.as_view()), name='delete_reason'),
    #Holidays
    path('holidays/', login_required(HolidaysGenericView.as_view()), name="list_holidays"),
    path('holidays/new', login_required(HolidaysCreateView.as_view()), name="new_holidays"), 
    path('holidays/<pk>/update', login_required(HolidaysUpdateView.as_view()), name='update_holidays'),
    path('holidays/<pk>/detail', login_required(HolidaysDetailView.as_view()), name='detail_holidays'),
    path('holidays/<pk>/delete', login_required(HolidaysDeleteView.as_view()), name='delete_holidays'),
    path('holidays/<pk>/report2', login_required(MyDetailViewPDF2.as_view()), name='report_holidays'),
    #Jefatura
    path('jefatura/', login_required(JefaturaGenericView.as_view()), name="list_jefatura"),
    path('jefatura/new', login_required(JefaturaCreateView.as_view()), name="new_jefatura"),
    path('jefatura/<pk>/update', login_required(JefaturaUpdateView.as_view()), name='update_jefatura'),
    path('jefatura/<pk>/detail', login_required(JefaturaDetailView.as_view()), name='detail_jefatura'),
    path('jefatura/<pk>/delete', login_required(JefaturaDeleteView.as_view()), name='delete_jefatura'),
    #Penalty
    path('penalty/', login_required(PenaltyGenericView.as_view()), name='list_penalty'),
    path('penalty/new', login_required(PenaltyCreateView.as_view()), name='new_penalty'),
    path('penalty/<pk>/update', login_required(PenaltyUpdateView.as_view()), name='update_penalty'),
    path('penalty/<pk>/detail', login_required(PenaltyDetailView.as_view()), name='detail_penalty'),
    path('penalty/<pk>/delete', login_required(PenaltyDeleteView.as_view()), name='delete_penalty'),
    #reportPenalty
    path('report/', login_required(ReportGenericView.as_view()), name='list_report_penalty'),
    #reportEmployee
    path('report/requirements', login_required(Report2GenericView.as_view()), name='list_report_permisos'),
]

employee/views.py
from django.views.generic import ListView, CreateView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from employee.forms import EmployeeForm, HolidayForm, JefaturaForm, LoginForm, PasswordChangeForm, PenaltyForm, RequirementForm, ReasonForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from employee.models import Employee, Jefatura, Penalty, Reason, Requirements, Holidays
from django.db.models import Sum, Q
from django.http import HttpResponseRedirect
import datetime


#Login
class Login(LoginView):
    template_name= 'login/login_form.html'
    form_class= LoginForm

class ChangePassword(PasswordChangeView):
    template_name= 'login/change_password.html'
    form_class= PasswordChangeForm
    success_url = '/employee/'


#Employe CRUD
class EmployeeGenericView(ListView):
    model = Employee
    paginate_by= 10
    context_object_name = 'employees'

    def get_queryset(self):
       result = super(EmployeeGenericView, self).get_queryset().order_by("-lastname")
       query = self.request.GET.get('search')
       if query:
           searchName = Employee.objects.filter(Q(identification__icontains=query)| Q(lastname__icontains=query)).order_by("-lastname")
           result = searchName
       else:
           result = Employee.objects.all()
       return result

class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm
    success_url= '/employee/'

class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm

    def get_success_url(self):
        return '/employee/'

class EmployeeDetailView(DetailView):
    model = Employee

class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = '/employee/'

#Requirements CRUD
class RequirementsGenericView(ListView):
    model = Requirements
    template_name= 'requirements/requirements_list.html'
    paginate_by= 10
    context_object_name = 'requirements'

    def get_queryset(self):
       result = super(RequirementsGenericView, self).get_queryset().order_by("-code")
       query = self.request.GET.get('search')
       if query:
           searchName = Requirements.objects.filter(Q(employee__lastname=query)|Q(code=query)).order_by("-code")
           result = searchName
       else:
           result = Requirements.objects.all()
       return result

class RequirementsCreateView(CreateView):
    model = Requirements
    template_name= 'requirements/requirements_form.html'
    form_class = RequirementForm
    success_url= '/requirements/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        requi = self.object
        dateEnd = requi.date_end
        dateStart = requi.date_start
        dif = dateEnd-dateStart
        minutes = dif.seconds / 60
        hours = divmod(minutes, 60)
        hd = hours[0]
        if hours[1]>40:
            hd = hd + 1
        requi.hours_discount = int(hd)
        requi.save()

        if requi.reason.penalty:
            Penalty.objects.create(hours_penalty=requi.hours_discount, observations=requi.reason.name,date=requi.date_requirement, requirement=requi)
        return HttpResponseRedirect(self.get_success_url())


class RequirementsUpdateView(UpdateView):
    model = Requirements
    template_name= 'requirements/requirements_form.html'
    form_class = RequirementForm

    def get_success_url(self):
        return '/requirements/'

class RequirementsDetailView(DetailView):
    model = Requirements
    template_name= 'requirements/requirements_detail.html'

class RequirementsDeleteView(DeleteView):
    model = Requirements
    success_url = '/requirements/'

#Reason CRUD
class ReasonGenericView(ListView):
    model = Reason
    paginate_by= 10
    template_name= 'reason/reason_list.html'
    context_object_name = 'reasons'

class ReasonCreateView(CreateView):
    model = Reason
    template_name= 'reason/reason_form.html'
    form_class = ReasonForm
    success_url= '/reason/'

class ReasonUpdateView(UpdateView):
    model = Reason
    template_name= 'reason/reason_form.html'
    form_class = ReasonForm
    def get_success_url(self):
        return '/reason/'

class ReasonDetailView(DetailView):
    model = Reason
    template_name= 'reason/reason_detail.html'

class ReasonDeleteView(DeleteView):
    model = Reason
    template_name= 'reason/reason_form.html'
    success_url = '/reason/'

#Holidays CRUD
class HolidaysGenericView(ListView):
    model = Holidays
    paginate_by= 10
    template_name= 'holidays/holidays_list.html'
    context_object_name = 'holidays'

    def get_queryset(self):
       result = super(HolidaysGenericView, self).get_queryset()
       query = self.request.GET.get('search')
       if query:
           result = Holidays.objects.filter(Q(employee__identification__icontains=query)| Q(employee__lastname__icontains=query)).order_by("-date_requirement")
       else:
           result = Holidays.objects.all().order_by("-date_job")
       return result

class HolidaysCreateView(CreateView):
    model = Holidays
    template_name= 'holidays/holidays_form.html'
    form_class = HolidayForm 
    success_url= '/holidays/'

    def get_context_data(self, **kwargs):
        context = super(HolidaysCreateView, self).get_context_data(**kwargs)
        context["employeeList"] = Employee.objects.all()
        employeeSelect = self.request.GET.get('employeeSelect')
        dateLastHolidays = self.request.GET.get('dateLastHolidays')
        if employeeSelect and dateLastHolidays:
            employee = Employee.objects.get(identification= employeeSelect)
            totalHoursPenalty = Penalty.objects.filter(requirement__employee__identification= employeeSelect, date__range=[dateLastHolidays, datetime.datetime.now()]).aggregate(Sum('hours_penalty'))
            try:
                hours_penalty = divmod(totalHoursPenalty["hours_penalty__sum"], 8)
                days = hours_penalty[0]
                hours = hours_penalty[1]
            except:
                days = 0
                hours = 0
            data = {'employee':employee, 'days': days, 'hours':hours}
            context['data']= data
        return context
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        holiday = self.object
        totalHoursPenalty = Penalty.objects.filter(requirement__employee__identification= holiday.employee.identification, date__range=[holiday.date_last_holidays, datetime.datetime.now()]).aggregate(Sum('hours_penalty'))
        hours_penalty = divmod(totalHoursPenalty["hours_penalty__sum"], 8)
        print(f'********{hours_penalty}')
        holiday.days_penalty = hours_penalty[0]
        day_solicitados = holiday.days + hours_penalty[0]
        if holiday.days_total - day_solicitados >= 0:
            holiday.days_take = day_solicitados
            holiday.days_pending =  holiday.days_total - holiday.days_take
            holiday.date_end = holiday.date_start + datetime.timedelta(days=holiday.days-1)
        else:
            holiday.days_take = holiday.days - hours_penalty[0]
            holiday.days_pending =  holiday.days_total - holiday.days
            holiday.date_end = holiday.date_start + datetime.timedelta(days=holiday.days-1) - datetime.timedelta(days=hours_penalty[0])

        holiday.entry_work = holiday.date_end + datetime.timedelta(days=1)
        holiday.save()
        return HttpResponseRedirect(self.get_success_url())

class HolidaysUpdateView(UpdateView):
    model = Holidays
    template_name= 'holidays/holidays_form.html'
    form_class = HolidayForm
    def get_success_url(self):
        return '/holidays/'

class HolidaysDetailView(DetailView):
    model = Holidays
    template_name= 'holidays/holidays_detail.html'

class HolidaysDeleteView(DeleteView):
    model = Holidays
    template_name= 'holidays/holidays_form.html'
    success_url = '/holidays/'

#Jefatura CRUD
class JefaturaGenericView(ListView):
    model = Jefatura
    paginate_by= 10
    template_name= 'jefatura/jefatura_list.html'
    context_object_name = 'jefaturas'

    def get_queryset(self):
       result = super(JefaturaGenericView, self).get_queryset()
       query = self.request.GET.get('search')
       if query:
           searchName = Jefatura.objects.filter(Q(description__icontains=query))
           result = searchName
       else:
           result = Jefatura.objects.all()
       return result

class JefaturaCreateView(CreateView):
    model = Jefatura
    template_name= 'jefatura/jefatura_form.html'
    form_class = JefaturaForm
    success_url= '/jefatura/'

class JefaturaUpdateView(UpdateView):
    model = Jefatura
    template_name= 'jefatura/jefatura_form.html'
    form_class = JefaturaForm
    def get_success_url(self):
        return '/jefatura/'

class JefaturaDetailView(DetailView):
    model = Jefatura
    template_name= 'jefatura/jefatura_detail.html'

class JefaturaDeleteView(DeleteView):
    model = Jefatura
    template_name= 'jefatura/jefatura_form.html'
    success_url = '/jefatura/'

#ReportPDF requerimiento
class MyDetailViewPDF(DetailView):
    # vanilla Django DetailView
    model = Requirements
    template_name = 'report/requirementsReport.html'

#ReportPDFHolidays
class MyDetailViewPDF2(DetailView):
    # vanilla Django DetailView
    model = Holidays
    template_name = 'report/holidaysReport.html'

    def get_context_data(self, **kwargs):
        object = super().get_context_data(**kwargs)
        date_diff = object['object'].date_end - object['object'].date_start
        object['date_diff'] = date_diff.days + 1
        # object['date_dif']= self.request.GET.get('days')-self.request.GET.get('days_penalty')
        return object

class PenaltyGenericView(ListView):
    model = Penalty
    paginate_by= 10
    template_name= 'penalty/penalty_list.html'
    context_object_name = 'penalties'

    def get_queryset(self):
        return super().get_queryset().order_by('-requirement__code')

employee/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema</title>
    <link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="{% static '/js/font-awesome.js' %}" crossorigin="anonymous"></script>
    <script src="{% static '/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static '/js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>

    </head>

<body>
    <div class="grid-home">
        <div>
            {% block sidebar %} {% endblock %}
        </div>

        <div>
            {% block content %} {% endblock %}
        </div>

        
        
        

    </div>

    {% block logout %} {% endblock %}



    {% block js %} {% endblock %}


</body>

</html>

employee/templates/logout.html
{% extends 'base.html' %} 

{% block logout %} 
<div>
    <h1 style="text-align: center;">A Cerrado su Sesion....!</h1>
</div>
<div>
    <h2 style="text-align: center;">Gracias por Confiar en nuestro Sistema, espero vuelvas pronto :)</h2>
    
    <a href="{% url 'login:login_form.html' %}" class="btn btn-primary">Volver a Login</a>
</div>
{% endblock %}

employee/templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="card-footer">
    <div class="d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a class="btn btn-outline-primary btn-sm" href="?page={{ page_obj.previous_page_number }}"><i
                    class="fa fa-chevron-circle-left" aria-hidden="true"></i></a>
            {% endif %}

            <span class="current">
                Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
            <a class="btn btn-outline-primary btn-sm" href="?page={{ page_obj.next_page_number }}"><i
                    class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}

employee/templates/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark w-25 vh-100 position-fixed">
  <a href="{% url 'employee:list_reason' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <label class="fs-4">ALCALDIA DE SANTA LUCIA</label>
  </a>
  <!-- nav-link active" aria-current="page" -->
  <hr>
  <ul id="items" class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a id="requerimientos" href="{% url 'employee:list_requirements' %}" onclick="handleItemActive('requerimientos')" class="nav-link text-white btn-outline-primary">
        Solicitud de Permisos
      </a>
    </li>
    <li class="nav-item">
      <a id="vacaciones" href="{% url 'employee:list_holidays' %}" onclick="handleItemActive('vacaciones')" class="nav-link text-white btn-outline-primary">
        Solicitud de Vacaciones
      </a>
    </li>
    <li class="nav-item">
      <a id="horas" href="{% url 'employee:list_penalty' %}" onclick="handleItemActive('horas')"class="nav-link text-white btn-outline-primary">
        Horas contabilizadas
      </a>
    </li>
    <li class="nav-item">
      <a id="empleados" href="{% url 'employee:list_employee' %}" onclick="handleItemActive('empleados')" class="nav-link text-white btn-outline-primary">
        Registro de Empleados
      </a>
    </li>
    <li class="nav-item">
      <a id="cargos" href="{% url 'employee:list_jefatura' %}" onclick="handleItemActive('cargos')" class="nav-link text-white btn-outline-primary">
        Registro de Cargo/Jefatura
      </a>
    </li>
    <li class="nav-item">
      <a id="motivos" href="{% url 'employee:list_reason' %}" onclick="handleItemActive('motivos')" class="nav-link text-white btn-outline-primary">
        Registro de Motivos
      </a>
    </li>
    <li class="nav-item">
      <a id="reporte_horas" href="{% url 'employee:list_report_penalty' %}" class="nav-link text-white btn-outline-primary">
        Reportes de Horas Contabilizadas
      </a>
    </li>
    <li class="nav-item">
      <a id="reporte_permisos" href="{% url 'employee:list_report_permisos' %}" class="nav-link text-white btn-outline-primary">
        Reportes de Permisos
      </a>
    </li>
  </ul>
  <hr>
  

  <div  div class="btn-group">
    <div class="btn-group dropup" role="group">
      <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropstart</span>
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{% url 'employee:change_password' %}" >Cambiar contraseña</a></li>
      </ul>
    </div>
    <a class="btn btn-danger w-100" href="{% url 'employee:logout' %}">Cerrar Sesión</a>
  </div>
</div>
<script>
  const itemActive = localStorage.getItem('itemActive')
  if(itemActive){
    console.log('item',itemActive)
    const el = document.getElementById(itemActive)
    el.className = "nav-link text-white btn-outline-primary active"
  }
  const handleItemActive = (id) => {
    localStorage.setItem('itemActive', `${id}`)
  }

</script>